### ISSUE TITLE
Suppression logic is wrong

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-web-component#12]
[Suppressions.sarif.txt](https://github.com/microsoft/sarif-web-component/files/4512703/Suppressions.sarif.txt)

Repro:

1. Save the attached file with extension `.sarif `.
2. Drag it onto the [web viewer](https://microsoft.github.io/sarif-web-component/).

Expected:

- results[0] should be visible (because it is not suppressed).
- results[1] should be hidden (because it is suppressed inSource).
- results[2] should be hidden (because it is suppressed externally).
- results[3] should be shown (because its suppression was rejected).

Actual:

- results[0] is visible: good
- results[1] is visible: bad
- results[2] is hidden: good
- results[3] is hidden: bad

A result should be shown _unless_ it has at least one suppression whose `status` is either missing or `accepted`.

**Comment by jeffersonking** [comment]
Fixed in 779316d9570fee01558a20ec450f9161a6da3123.

**Comment by lgolding** [comment]
@jeffersonking 

Hi Jeff,

In @michaelfanning's review of the [samples PR](https://github.com/microsoft/sarif-tutorials/pull/12), he argued -- and I agree -- that if a suppression is still under review, it should be hidden until it is explicitly rejected. So please change the logic as follows:

```
IF there are no suppressions OR all suppressions are rejected THEN
    show it
ELSE
    // There is at least one suppression that has not been rejected: either it has been accepted,
    // or it is still under review, or it has no status.
    hide it
ENDIF 
```

**Comment by lgolding** [comment]
@harleenkohli, why did you reopen this? Did you see the same issue in @jeffersonking's latest extension?

**Comment by lgolding** [comment]
Ok, I understand now -- re-closing.
