### ISSUE TITLE
Don't duplicate rule.id/rule.name

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-web-component#18]
If `rule.id` is the same as `rule.name` (which violates SARIF, but oh well), don't display both:

![DuplicateRuleIdRuleName](https://user-images.githubusercontent.com/11762653/82463289-80bbe180-9a71-11ea-8dd9-757d38e1173a.png)

**Comment by jeffersonking** [comment]
We discussed this issue and decided this should be fixed on the SARIF producer side.
