### ISSUE TITLE
Wrong number of characters highlighted

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-web-component#23]
The attached SARIF file [highlight.sarif.txt](https://github.com/microsoft/sarif-web-component/files/5358015/highlight.sarif.txt) describes an issue in the attached source file [highlight.cs.txt](https://github.com/microsoft/sarif-web-component/files/5358016/highlight.cs.txt).

In the [Web viewer](https://microsoft.github.io/sarif-web-component/), the correct range of 5 characters is highlighted:

![image](https://user-images.githubusercontent.com/11762653/95639022-aca12900-0a4b-11eb-9f10-f471b9c18363.png)

But when I file a bug in ADO and attach the same SARIF file, the Scans Tab highlights only three columns:

![image](https://user-images.githubusercontent.com/11762653/95639166-508ad480-0a4c-11eb-8187-dac77bf4e72e.png)

**Comment by jeffersonking** [comment]
Caused by a charset issue. Described for future readers here: d7d24cb326ca240e5af46c7995b8c504604679fd.

The fix is implemented in the page hosting this component. I have fixed the instances what we own.
