### ISSUE TITLE
Not able to dismiss the tooltip of "Clear Filters" button and "1" control using the "Esc" key

### ISSUE THREAD

**Issue by shreyashi227** [microsoft/sarif-web-component#25]
### Actual:
When we navigate to "Clear Filters" button and "1" control using Tab key tooltip appears but we are not able to dismiss the tooltip of "Clear Filters" button and "1" control using the "Esc" key

### Expected:
The user should be able to dismiss the tooltip of "Clear Filters" button and "1" control using the "Esc" key

**Comment by jeffersonking** [comment]
Fixed in v0.5 (2413b17b8cf2f5a11cf4238df5418f00eddd43a1). Thanks for reporting!
