### ISSUE TITLE
Incorrect control type "Group" exist for "Filter" control.

### ISSUE THREAD

**Issue by shreyashi227** [microsoft/sarif-web-component#27]
### Actual:
The given control type for "Filter" control is "Group" but this control is working as a "Button" 

### Expected:
The correct control type should be provided for the "Filter" control that is "Button".

**Comment by jeffersonking** [comment]
I am uncertain what you mean by "control type". If you are using terminology specific to a particular screen reader, I ask that you refer to them in standard ARIA terms.

If by "control type" you mean the ARIA role, I am not seeing any element with a role of "group". Could you attach a screenshot to "point at" which element you are referring to?

**Comment by shreyashi227** [comment]
@jeffersonking 
When we are checking with Accessibility Insights for Desktop the control type is given as "Group" and Localized Control Type has been provided as "search". After verifying the issue with screen reader it is announcing "search filter by keywords" so for the screen reader users will not be able to understand how to interact with the control as there is no announcement for the control type for ex "edit". So here the screen reader should announce "search filter by keyword edit".

**Comment by jeffersonking** [comment]
Should be fixed in v0.5 (2413b17b8cf2f5a11cf4238df5418f00eddd43a1).

I see the control type as "edit" via Accessibility Insights for Windows. However, I am not an expert with that app so can you verify again? You can access the new version here: https://microsoft.github.io/sarif-web-component/

Thanks!
